### PR TITLE
Added support to RedProtect, and some improvements

### PR DESCRIPTION
**Pull request by FabioZumbi12**
Added support to RedProtect, auto name sign if placed under region and deny self buy/rent.

### CODE REVIEW

**Comment by dsevillamartin** [comment]
Oh wow... I didn't expect anyone to actually contribute to the plugin lol.

Thanks for the contribution! I'll test it out and make sure things work as they should, and if they do I'll merge and publish a new version after pushing some minor adjustments.

**Comment by FabioZumbi12** [comment]
This additions dont only allows redprotect support but allow any other antigrief additions, because i've added a interface to be easy to add more compatible plugins ^^

I just added my plugin, but if you want this plugin to be more popular, you can add GP too.

**Comment by dsevillamartin** [comment]
@FabioZumbi12 Oh, that's great! Thanks man!

**Comment by dsevillamartin** [comment]
@FabioZumbi12 Can I have the RedProtect 2.6.0 b200 JAR file? I am unable to build it from source so I can't test stuff with it nor compile BuyRegion.

**Comment by FabioZumbi12** [comment]
Oh shure, you can download from here (ignore the security message): https://host.areaz12server.net.br:8080/job/RedProtect/

**Comment by dsevillamartin** [comment]
After some testing, this seems to work great !
I added a log to show in the console what region plugin is being used, a contributors list when enabling the plugin where I moved your name to (and added that you updated it to 1.14 as well), and fixed a NullPointerException when the plugin was disabled as a result of no economy plugin or region manager being found.

Thank you for the auto name & reload command, didn't even realize you added it until writing this comment, and I even used it to reload my language file xD.

Changed the version to 2.2.0 as it's a minor update, not a patch (has features).

Thanks for the contribution, man!

image

**Comment by dsevillamartin** [comment]
TYSM 💯 

https://www.spigotmc.org/resources/buyregion-1-13.60189/update?update=276640

**Pull request merged**
